name       : sbt
version    : 1.3.13
release    : 9
source     :
    - git|https://github.com/sbt/sbt.git : v1.3.13
license    : Apache-2.0
component  : programming.tools
summary    : Build tool for Scala, Java, and more
description: |
    sbt is an open-source build tool for Scala and Java projects, similar to Apache's Maven and Ant.
builddeps  :
    - sbt
rundeps    :
    - openjdk-11
networking : yes
setup      : |
    sed -e 's|-SNAPSHOT||g' -i build.sbt
build      : |
    # Can be removed on the next release.
    export PATH="$PATH:/usr/lib64/openjdk-11/bin"

    sbt -Divy.home=$workdir/.ivy2 \
        -Dsbt.boot.lock=false \
        -Dsbt.global.base=$workdir/.sbt \
        -Dsbt.ivy.home=$workdir/.ivy2 \
        -Duser.home=$workdir/.java \
        package
install    : |
    install -Dm00755 $pkgfiles/sbt.sh $installdir/usr/bin/sbt
    install -Dm00644 launch/target/sbt-launch.jar $installdir/usr/share/sbt/sbt.jar
