name       : sbt
version    : 0.13.13
release    : 2
source     :
    - https://github.com/sbt/sbt/archive/v0.13.13.tar.gz : 39ac67e12096217ddbfe06708f0d36fe03b654af306f231b6f713739aceb66b4
    - https://dl.bintray.com/sbt/native-packages/sbt/0.13.13/sbt-0.13.13.tgz : 40d03d21a260c5a6a43f8349298f41c9d047f97972057d9d915afd8945faf979
license    : BSD-3-Clause
component  : programming.tools
summary    : sbt is a build tool for Scala, Java, and more.
description: |
    sbt is a build tool for Scala, Java, and more.
builddeps  :
    - openjdk-8
setup      : |
    tar -xvf $sources/sbt-$version.tgz
build      : |
    sbt-launcher-packaging-$version/bin/sbt package
install    : |
    install -D -m 00755 $pkgfiles/sbt.sh $installdir/usr/share/sbt/sbt.sh
    install -D -m 00644 launch/target/sbt-launch.jar $installdir/usr/share/sbt/sbt-launch.jar
    install -d $installdir/usr/bin
    ln -s  /usr/share/sbt/sbt.sh $installdir/usr/bin/sbt