name       : sbt
version    : 0.13.15
release    : 4
source     :
    - https://github.com/sbt/sbt/archive/v0.13.15.tar.gz : 83e40dbcb588d98812dc1151a089370b65c0a6bfd2081c243a6ce2aefbd92c25
license    : BSD-3-Clause
component  : programming.tools
summary    : sbt is a build tool for Scala, Java, and more.
description: |
    sbt is a build tool for Scala, Java, and more.
builddeps  :
    - openjdk-8
    - sbt
networking : yes
build      : |
    sbt -Dsbt.global.base=./.sbt/ -Dsbt.ivy.home=./.ivy2/ -Divy.home=./.ivy2/ package
install    : |
    install -D -m 00755 $pkgfiles/sbt.sh $installdir/usr/share/sbt/sbt.sh
    install -D -m 00644 launch/target/sbt-launch.jar $installdir/usr/share/sbt/sbt-launch.jar
    install -d $installdir/usr/bin
    ln -s  /usr/share/sbt/sbt.sh $installdir/usr/bin/sbt
