name       : sbt
version    : 1.3.10
release    : 6
source     :
    # sbt expects a git repository in order to be built.
    - git|https://github.com/sbt/sbt.git : v1.3.10
license    : Apache-2.0
component  : programming.tools
summary    : Build tool for Scala, Java, and more
description: |
    sbt is a build tool for Scala, Java, and more.
builddeps  :
    - openjdk-8 # Can be removed on the next release.
    - sbt
rundeps    :
    - openjdk-8
networking : yes
setup      : |
    sed -e 's|-SNAPSHOT||g' -i build.sbt
build      : |
    # Can be removed on the next release.
    export PATH="$PATH:/usr/lib64/openjdk-8/bin"

    sbt -Divy.home=$workdir/.ivy2 \
        -Dsbt.global.base=$workdir/.sbt \
        -Dsbt.ivy.home=$workdir/.ivy2 \
        -Duser.home=$workdir/.java \
        package
install    : |
    install -Dm00755 $pkgfiles/sbt.sh $installdir/usr/bin/sbt
    install -Dm00644 launch/target/sbt-launch.jar $installdir/usr/share/sbt/sbt.jar
